# Generated by Django 5.2.9 on 2025-12-22 23:42

import django.db.models.deletion
import django.utils.timezone
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True, verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('etapa', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('conteudo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('Domingo', 'Domingo'), ('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado')], max_length=7)),
                ('horaInicio', models.TimeField()),
                ('horaFim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('matricula', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True, verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('codigo', models.CharField(default=secrets.token_urlsafe, max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('status', models.BooleanField(default=False)),
                ('criadoEm', models.DateTimeField(default=django.utils.timezone.now)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadas.aula')),
            ],
        ),
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horaEntrada', models.DateTimeField(blank=True, null=True)),
                ('horaSaida', models.DateTimeField(blank=True, null=True)),
                ('faltas', models.IntegerField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadas.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadas.aula')),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamadas.chave')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='diario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadas.diario'),
        ),
        migrations.AddField(
            model_name='diario',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadas.disciplina'),
        ),
        migrations.AddField(
            model_name='aula',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamadas.horario'),
        ),
        migrations.AddField(
            model_name='diario',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chamadas.professor'),
        ),
    ]
