# Generated by Django 5.2.9 on 2025-12-04 04:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True, verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('numAula', models.IntegerField()),
                ('conteudo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('turno', models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=20)),
                ('curso', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horaInicio', models.TimeField()),
                ('horaFim', models.TimeField()),
                ('tolerancia', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('matricula', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True, verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('status', models.BooleanField(default=False)),
                ('criadoEm', models.DateTimeField(default=django.utils.timezone.now)),
                ('usadoEm', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chamadas.aluno')),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chamadas.aula')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='diario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadas.diario'),
        ),
        migrations.AddField(
            model_name='diario',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadas.disciplina'),
        ),
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horaEntrada', models.DateTimeField(blank=True, null=True)),
                ('horaSaida', models.DateTimeField(blank=True, null=True)),
                ('presencas', models.IntegerField(default=0)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadas.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadas.aula')),
                ('chave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamadas.chave')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamadas.horario')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamadas.horario'),
        ),
        migrations.AddField(
            model_name='diario',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chamadas.professor'),
        ),
    ]
