# Generated by Django 5.2.9 on 2025-12-04 04:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True, verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horaInicio', models.TimeField()),
                ('horaFim', models.TimeField()),
                ('tolerancia', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='diario',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chamadas.professor'),
        ),
        migrations.AlterField(
            model_name='diario',
            name='turno',
            field=models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno')], max_length=30),
        ),
        migrations.AlterField(
            model_name='professor',
            name='matricula',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='senha',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('numAula', models.IntegerField()),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadas.diario')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamadas.horario')),
            ],
        ),
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('status', models.BooleanField(default=False)),
                ('criadoEm', models.DateTimeField(default=django.utils.timezone.now)),
                ('usadoEm', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chamadas.aluno')),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chamadas.aula')),
            ],
        ),
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horaEntrada', models.DateTimeField(blank=True, null=True)),
                ('horaSaida', models.DateTimeField(blank=True, null=True)),
                ('presencas', models.IntegerField(default=0)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadas.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadas.aula')),
                ('chave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamadas.chave')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamadas.horario')),
            ],
        ),
    ]
